import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const outfit = Outfit({
  subsets: ["latin"],weight:["400","500","600","700"]
});
const ovo = Ovo({
  subsets: ["latin"],weight:["400"]
});




export const metadata = {
  title: "Priyanshu's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden `}

      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
